apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ppctlr
    app.kubernetes.io/component: controller
  name: "{{ .Release.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ppctlr
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ppctlr
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: ppctlr-controller
      containers:
      - name: controller
        image: "{{ .Values.Image }}"
        imagePullPolicy: "{{ if .Values.Local }}Never{{ else }}Always{{ end }}"
        command:
        - "/ko-app/pool-policy-controller"
        - "-v=5"
        - "--namespace=$(POD_NAMESPACE)"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      serviceAccount: ppctlr-controller
