apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: ppctlr
    app.kubernetes.io/component: controller
  name: ppctlr-controller
rules:
- apiGroups: [ "" ]
  resources: [ configmaps ]
  verbs: [ get, list, watch ]
- apiGroups: [ "" ]
  resources: [ pods ]
  verbs: [ get, list, watch, create, update, patch, delete ]

- apiGroups: [ "llmd.ai" ]
  resources: [ launcherpoolpolicies ]
  verbs: [ get, list, watch, create, update, patch, delete ]
