apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: ppctlr
    app.kubernetes.io/component: controller
  name: ppctlr-controller-in-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ppctlr-controller
subjects:
- kind: ServiceAccount
  name: ppctlr-controller
  namespace: "{{ .Release.Namespace }}"
{{if .Values.NodeViewClusterRole}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: ppctlr
    app.kubernetes.io/component: controller
  name: ppctlr-controller-node-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ .Values.NodeViewClusterRole }}"
subjects:
- kind: ServiceAccount
  namespace: "{{ .Release.Namespace }}"
  name: ppctlr-controller
{{end }}
