Image: ghcr.io/llm-d-incubation/pool-policy-controller:latest

# Set this to true when deploying in a local cluster.
Local: false

# Name of the ClusterRole to bind to controller to authorize it to
# get/list/watch Node objects.
# Empty string means no new binding is needed.
NodeViewClusterRole: ""

# Optional: namespace the controller should focus on (watch only this namespace).
# If empty the controller will watch all namespaces.
WatchNamespace: ""
